### ISSUE TITLE
Pinned Item Changes not Persisting

### ISSUE THREAD

**Issue by User-Epix** [ciderapp/Cider-2#246]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Built on 01/06/2023, 23:39:07 | Quasar V2.12.0 | Electron 2467d63e5879calb4edef87f1687b870ed42d8e4

### Operating System Version

macOS Ventura 12.4 (22F66)

### Describe the Bug

If a song has been pinned, unpinning it from the home page or anywhere seems to remove it for that session. reopening the app results in it coming back

### Steps to Reproduce

1. Pin any song to home
2. Restart cider or continue without restarting
3. Try to unpin it from home
4. Relaunch Cider and it returns

### Anything else?

 
  

https://github.com/ciderapp/Cider-2/assets/120188870/7e0a623f-f9c3-43c4-836c-294a76c88a27

### Build timestamp

1686386191496
```[tasklist]
### Tasks
```

**Comment by coredev-uk** [comment]
I'm guessing you're logged into connect?

**Comment by cryptofyre** [comment]
Fixed in 2.2.0
